[package]
name = "rs_lib"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
conventional-prs = { path = ".." }
serde_json = "1.0"
serde_yaml = "0.9"
wasm-bindgen = "=0.2.106"
